version: '3'
services:
  ganache:
    build: ganache
    image: ganache:wallet
    container_name: ganache-cli
    tty: true
    volumes:
      - ./ganache/src:/usr/src/app
      - ./ganache/db:/var/ganache
    ports: 
      - "8545:8545"
  truffe:
    build: truffle
    image: truffle
    container_name: truffle
    tty: true
    volumes:
      - ./truffle/src:/usr/app/src
    ports: 
      - "3000:3000"
  frontend:
    build: frontend
    image: react-frontend
    container_name: react
    tty: true
    volumes: 
      - ./frontend/src:/usr/app/src
    ports: 
      - "3333:3000"
      - "9090:8080"
  nodebackend:
    build: nodeserver
    image: nodeserver
    container_name: nodebackend
    tty: true
    volumes:
      - ./nodeserver/src:/usr/app/src
    ports:
      - "5555:5555"
  mongodb:
    image: mongo:4.2.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./mongodb/mongo_db:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:0.49.0
    container_name: mongo-express
    restart: always
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
networks:
  default:
    external:
      name: dapp_dev_01